### ISSUE TITLE
Should we move these functions to StationShiftController?

### ISSUE THREAD

**Issue by tavorperry** [tavorperry/Kafe_Emon#24]
**Should we move these functions to StationShiftController?**
1. sendNotificationstoUsers
2. getUsersInCurrentShift
3. getCurrentShift

They are now written in ReportController because when a report has been reported the function searches for the users in the current shift in order to send notifications to all of them, but I think it's better to put them on StationShiftsContorller.
**What do you think?**
@cygelman

**Comment by cygelman** [comment]
Didn't we solve that issue?

**Comment by tavorperry** [comment]
No, Maybe we need move it to user

**Comment by cygelman** [comment]
Do they have to be in the same model?

**Comment by tavorperry** [comment]
It's recommended cause they all part of the same process...
